USE GalloTubeDb;

INSERT INTO Tag(Id, Name) VALUES

(1, '#Documentarios'),

(2, '#Jogos'),

(3, '#Futebol'),

(4, '#Carros'),

(5, '#Desenhos'),

(6, '#Roupas'),

(7, '#Séries'),

(8, '#Comédia'),

(9, '#Animes'),

(10,'#Música'),

INSERT INTO Video VALUES
( 1, 'A maldição do TRIÂNGULO DAS BERMUDAS', 'History oferece séries, documentários e produções originais que não apenas entretêm, mas conectam você com seu lado curioso e emocional. Convidamos você a conhecer a história por trás da história, a explorar o misterioso, o desconhecido e o intrigante. Este é o ponto de encontro para responder a perguntas sobre o passado ou encontrar uma perspectiva diferente de fatos históricos.', "2023-04-15 00:41:02", 42, '\\img\\1.png', 'https://youtu.be/ogbK7pybGyE?feature=shared');

INSERT INTO Video VALUES
( 5, 'Pica-Pau em Português | Pica-Pau fica louco por um sorvete | Desenhos para crianças', 'Pica-Pau e seus amigos estão divertindo o mundo há mais de 80 anos. Sempre encontrando uma maneira de sair bicando por aí e fugir dos problemas, Pica-Pau ganhou seu status como um verdadeiro Ícone da Cultura Pop. Pica-Pau tem uma estrela na Calçada da Fama de Hollywood e Walter Lantz ganhou um Oscar honorário com o Pica-Pau em 1979. ', "2023-03-31 01:01:51", 62, '\\img\\2.png', 'https://youtu.be/mzX4pFfHHaI?feature=shared');

INSERT INTO Video VALUES
( 10, 'I Wanna be yours', '℗ 2013 Domino Recording Co Ltd

Released on: 2013-09-09

Producer: James Ford
Producer: Ross Orton
Mixer: Tchad Blake
Music  Publisher: EMI Music Publishing Ltd
Composer: Arctic Monkeys
Lyricist: John Cooper Clarke

Auto-generated by YouTube.', "2014-12-09 00:03:03", 04, '\\img\\3.png', 'https://youtu.be/nyuo9-OjNNg?feature=shared');

INSERT INTO VideoTag VALUES
( 1, 1);

( 5, 5);

( 10, 10);