USE GalloTubeDb;

INSERT INTO Tag(Id, Name) VALUES

(1, '#Documentarios'),

(2, '#Jogos'),

(3, '#Futebol'),

(4, '#Carros'),

(5, '#Desenhos'),

(6, '#Roupas'),

(7, '#Séries'),

(8, '#Comédia'),

(9, '#Animes'),

(10,'#Música'),

INSERT INTO Video VALUES
( 1, 'A maldição do TRIÂNGULO DAS BERMUDAS', 'History oferece séries, documentários e produções originais que não apenas entretêm, mas conectam você com seu lado curioso e emocional. Convidamos você a conhecer a história por trás da história, a explorar o misterioso, o desconhecido e o intrigante. Este é o ponto de encontro para responder a perguntas sobre o passado ou encontrar uma perspectiva diferente de fatos históricos.', "2023-04-15 00:41:02", 42, '\\img\\1.png', 'https://youtu.be/ogbK7pybGyE?feature=shared');

INSERT INTO Video VALUES
( 2, 'CBLOL 2023: 2ª Etapa - Playoffs | paiN Gaming x LOUD (Jogo 1)', 'CBLOL 2023: 2ª Etapa - Assista ao VOD da primeira partida da Md5 entre  paiN Gaming (PNG) x LOUD (LLL) nos Playoffs.', "2023-08-20 01:02:11", 63, '\\img\\4.png', 'https://youtu.be/X6EI7WfLvEQ?si=iGxvKcGBK1JD4_OI');

INSERT INTO Video VALUES
( 3, 'GRÊMIO 2 X 0 CUIABÁ | MELHORES MOMENTOS | 22ª RODADA DO BRASILEIRÃO 2023 | ge.globo', 'O Grêmio venceu o Cuiabá por 2 a 0, na Arena do Grêmio, em duelo válido pela 22ª rodada do Campeonato Brasileiro. Suárez, no primeiro tempo, e Rikelme (contra), na etapa final, fizeram os gols da partida.', "2023-09-03 00:03:18", 04, '\\img\\5.png', 'https://youtu.be/Y_LySqfDBpw?si=03HCBbtF1n7UIy9S');

INSERT INTO Video VALUES
( 4, 'CARROS RUINS DE QUEBRAR e ECONÔMICOS ! NÃO GOSTAM DE MECÂNICO NEM DE POSTO!', 'Hoje quase todo mundo quando quer comprar um carro novo, seminovo ou usado, procura um carro econômicos, muito confiável, resistente e barato de manter, com boa oferta de peças e mão de obra barata né? Então vou te recomendar os carros mais econômicos que são difíceis de quebrar e baratos de manter! Bora pro vídeo conferir!
', "2022-04-13 00:17:16", 18, '\\img\\6.png', 'https://youtu.be/3t49jDRJREo?si=71s_dM0g3nFMPU5B');

INSERT INTO Video VALUES
( 5, 'Pica-Pau em Português | Pica-Pau fica louco por um sorvete | Desenhos para crianças', 'Pica-Pau e seus amigos estão divertindo o mundo há mais de 80 anos. Sempre encontrando uma maneira de sair bicando por aí e fugir dos problemas, Pica-Pau ganhou seu status como um verdadeiro Ícone da Cultura Pop. Pica-Pau tem uma estrela na Calçada da Fama de Hollywood e Walter Lantz ganhou um Oscar honorário com o Pica-Pau em 1979. ', "2023-03-31 01:01:51", 62, '\\img\\2.png', 'https://youtu.be/mzX4pFfHHaI?feature=shared');

INSERT INTO Video VALUES
( 6, 'CHEGARAM MINHAS COMPRAS DA PROMOÇÃO DA SHEIN! (Expectativa e realidade da Shein)', 'Fiz algumas compras na promoção da Shein e vamos ver se as roupas são iguais nas fotos mesmo
Instagram: https://www.instagram.com/_feliperica...', "2023-05-22 00:11:55", 12, '\\img\\7.png', 'https://youtu.be/dQtYA27H7ME?si=vCtmP5gVzDBPr_Ww');

INSERT INTO Video VALUES
( 7, 'ONE PIECE: A Série | Trailer final | Netflix', 'Um tesouro mítico, piratas poderosos e um bando lendário. 🏴‍☠️ #OnePieceNetflix zarpa em 31 de agosto, só na Netflix.', "2023-08-30 00:02:22", 03, '\\img\\8.png', 'https://youtu.be/raL1367FIl0?si=zG9cpEs88UaS-lka');

INSERT INTO Video VALUES
( 8, '1 HORA de COMÉDIA | VÍDEOS ENGRAÇADOS | TENTE NÃO RIR IMPOSSÍVEL ', 'Temos uma ampla variedade de vídeos de COMÉDIA para atender a todos os gostos, incluindo tombos, pegadinhas, memes, desafios de "tente não rir", animais engraçados, trollagens e muito mais. Se você gostou de nossa seleção de memes e vídeos ENGRAÇADOS , te convido a fazer parte da nossa família.', "2023-08-20 01:00:09", 61, '\\img\\9.png', 'https://youtu.be/wjXKTOc_ChY?si=BJYahZ3o9HmFA6dD');

INSERT INTO Video VALUES
( 9, 'Garoto POBRE Possui os MAIORES PODERES MÁGICOS e Derrota o DRAGÃO de Ossos ANCESTRAL LENDÁRIO', ' O Anime acompanha a vida de Shingo Ichinomiya, um rapaz de 25 anos imerso na rotina de sua carreira corporativa. Enquanto contempla mais um dia de trabalho à frente, ele é surpreendido por um sono profundo. Ao despertar, entretanto, Shingo se depara com uma realidade completamente diferente: está em um ambiente desconhecido e percebe que sua consciência foi misteriosamente transferida para o corpo de uma criança de apenas 5 anos.', "2023-08-18 00:38:33", 39, '\\img\\10.png', 'https://youtu.be/ZjYDfuOBzeE?si=lSc3q5PLgpulGrud');

INSERT INTO Video VALUES
( 10, 'I Wanna be yours', '℗ 2013 Domino Recording Co Ltd

Released on: 2013-09-09

Producer: James Ford
Producer: Ross Orton
Mixer: Tchad Blake
Music  Publisher: EMI Music Publishing Ltd
Composer: Arctic Monkeys
Lyricist: John Cooper Clarke

Auto-generated by YouTube.', "2014-12-09 00:03:03", 04, '\\img\\3.png', 'https://youtu.be/nyuo9-OjNNg?feature=shared');

INSERT INTO VideoTag VALUES
( 1, 1);

( 2, 2);

( 3, 3);

( 4, 4);

( 5, 5);

( 6, 6);

( 7, 7);

( 8, 8);

( 9, 9);

( 10, 10);


